### ISSUE TITLE
Create Postman Collection

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/PostmanFun#1]
Create a new branch, and open a pull request to this repo with the following changes.

Create a Postman collection called "PJ", it should contain:

- [x] A Create User call
- [x] A Get User call
- [x] An Update User call
- [x] A Delete User call
- [x] The provided Get All Users Call

Export the collection from Postman as a .json file and place it in the base directory of this repository.

**Comment by Jeremy-Barnes** [comment]
Provided Get All Users call (create this in your postman collection)

![image](https://user-images.githubusercontent.com/2288705/193384256-c9bb4e12-0612-43bc-975b-916654bcd7a7.png)

**Comment by MonteCrisply** [comment]
Done!
